import Head from "next/head";
import Banner from "../components/optimum/Banner/Banner";
import Header from "../components/optimum/Header/Header";
import OptimumBox from "../components/optimum/OptimumBundls/OptimumBox";
import OptimumWrraper2 from "../components/optimum/OptimumWrapper2/OptimumWrapper2";
import OptimumWrapper from "../components/optimum/OptimumWrapper/OptimumWrapper";
import OptimumFAQS from "../components/optimum/OptimumFAQS/OptimumFAQS";
import OptimumFooter from "../components/optimum/Footer/OptimumFooter";
import Script from "next/script";

export default function Optimum() {
  return (
    <>
    <Script id="faq-optimum" type="application/ld+json">
    {`{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [{
    "@type": "Question",
    "name": "How can I get Optimum?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "You can easily get Optimum by Altice. Simply follow this link. All you need is your ZIP code and you can easily choose from a variety of Optimum services and plans available in your area."
    }
  },{
    "@type": "Question",
    "name": "How to pay my Optimum bill?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Reach out to Cox customer service for assistance regarding billing by dialing +1+1(800) 962-3418."
    }
  },{
    "@type": "Question",
    "name": "What is Altice Optimum?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Optimum by Altice is an American cable provider with residential and business subscribers in 21 states. As an MSO the company handles the brand Optimum, associated with Internet, TV and Voice offerings, which it plans to expand and rebrand in the near future."
    }
  },{
    "@type": "Question",
    "name": "Is Optimum available in my area?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Optimum is a cable provider mostly found in New York, New Jersey, Connecticut and other states. To see if this ISP is offering services in your area, check our coverage map."
    }
  },{
    "@type": "Question",
    "name": "Is Optimum customer service 24 hours?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Yes. Optimum’s customer service and technical support lines are open 24/7, so you can call any time you have a query about the provider. However, all other support agents are available from 8 to 8 on business days."
    }
  }]
}`}

    </Script>
      <Head>
        <title>Optimum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index,follow" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="xfinity_wrapper"
        style={{ background: "#000", overflow: "hidden" }}
      >
        <Header />
        <Banner />
        {/* <OptimumBundls/> */}
        <OptimumBox />
        <OptimumWrapper />
        <OptimumWrraper2 />
        <OptimumFAQS />
        <OptimumFooter />
      </main>
    </>
  );
}
