import Head from "next/head";
import Banner from "../components/phone-service/banner/Banner";
import LatestBlogs from "../components/phone-service/latest-blogs/LatestBlogs";
import PhonePackages from "../components/phone-service/phone-packages/PhonePackages";
import ProviderBenifits from "../components/phone-service/phone-providers/ProviderBenifits";
import TopProviders from "../components/phone-service/top-providers/TopProviders";
import Yiptrustbox from "../components/services/yip-trust/Yiptrustbox";
import getBlogs from "../controllers/getBlogs";


const PhoneService = ({data}:any) => {
  return (
    <>
       <Head>
            <title>Phone Services</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <div className="providers_page_bg">
            <div className="providers_page_bg_inner">
                <ProviderBenifits />
                <PhonePackages />
                <TopProviders />
                <Yiptrustbox />
                <LatestBlogs blogs={data} />
            </div>
        </div>
      </main>
    </>
  )
}
export async function getStaticProps() {

  const response = (await getBlogs(1, 5)) as [];
  if (response.length < 1) {
    return {
      props: {
        data: [],
      },
    };
  }
  return {
    props: {
      data: response,
    },
  };
}
export default PhoneService;
